[workspace]
members = [ "color", "geometry", "utility" ]
default-members = [ "color", "geometry", "utility" ]

[package]
name = "rust-v"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bitmask flag generator
bitflags = ""
# Program argument parser
clap = { version = "", features = ["yaml"] }
# fast random types
fastrand = ""
# image loading / saving
image = ""
# progress bars etc.
indicatif = ""
# lazy statics / consts refs
lazy_static = ""
# num of logical / physical cpus
num_cpus = ""
# small vectors for bsdf e.g.
smallvec = ""
# linear algebra
ultraviolet = { version = "", features= ["int"] }

color = { path = "./color" }
geometry = { path = "./geometry" }
utility = { path = "./utility" }

[features]
default = []
live-window = [] #["show-image"]

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
incremental = true