[workspace]
members = [ "color", "geometry", "scenes", "utility" ]
default-members = [ "color", "geometry", "scenes", "utility" ]

[package]
name = "rust-v"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bitmask flag generator
bitflags = ""
# fast random types
fastrand = ""
# progress bars etc.
indicatif = ""
# linear algebra
ultraviolet = { version = "", features= ["int"] }

color = { path = "./color" }
geometry = { path = "./geometry" }
utility = { path = "./utility" }
