[workspace]
members = [ "color", "demos", "geometry", "utility" ]
default-members = [ "color", "demos", "geometry", "utility" ]

[package]
name = "rust-v"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bitmask flag generator
bitflags = ""
# Program argument parser
clap = { version = "", features = ["yaml"] }
# fast random types
fastrand = ""
# image loading / saving
image = ""
# progress bars etc.
indicatif = ""
# num of logical / physical cpus
num_cpus = ""
# live image of rendering
show-image = { version = "0.6.5", features = ["image", "save"], optional = true }
# linear algebra
#ultraviolet = { version = "", features= ["int", "serde"] }
ultraviolet = { path = "./ultraviolet", features= ["int", "serde"] }

# De-/Serialization
serde = { version = "", features = ["derive", "rc"] }
typetag = ""
ron = ""

color = { path = "./color" }
geometry = { path = "./geometry" }
utility = { path = "./utility" }

[dev-dependencies]
criterion = ""

[[bench]]
name = "refractive_index"
harness = false

[features]
default = []
live-window = ["show-image"]

[profile.release]
#codegen-units = 1
opt-level = 3
lto = true
incremental = true

[profile.dev]
incremental = true
