[package]
name = "geometry"
version = "0.1.0"
authors = ["Julius Oeftiger <j.oeftiger@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tobj = ""
ultraviolet = { version = "", features = ["serde"] }
serde = { version = "", features = ["derive"] }

utility = { path = "../utility" }